/* eslint-disable */
// this is an auto generated file. This will be overwritten

export const onCreateAccount = /* GraphQL */ `
  subscription OnCreateAccount {
    onCreateAccount {
      id
      name
      status
      type
      address {
        address1
        address2
        city
        stateProvince
        postalCode
        country
      }
      externalReferences
      createdAt
      updatedAt
      _version
      _deleted
      _lastChangedAt
    }
  }
`;
export const onUpdateAccount = /* GraphQL */ `
  subscription OnUpdateAccount {
    onUpdateAccount {
      id
      name
      status
      type
      address {
        address1
        address2
        city
        stateProvince
        postalCode
        country
      }
      externalReferences
      createdAt
      updatedAt
      _version
      _deleted
      _lastChangedAt
    }
  }
`;
export const onDeleteAccount = /* GraphQL */ `
  subscription OnDeleteAccount {
    onDeleteAccount {
      id
      name
      status
      type
      address {
        address1
        address2
        city
        stateProvince
        postalCode
        country
      }
      externalReferences
      createdAt
      updatedAt
      _version
      _deleted
      _lastChangedAt
    }
  }
`;
export const onCreateUser = /* GraphQL */ `
  subscription OnCreateUser {
    onCreateUser {
      id
      username
      email
      avatarKey
      description
      pushToken
      accountID
      userType
      createdAt
      updatedAt
      _version
      _deleted
      _lastChangedAt
    }
  }
`;
export const onUpdateUser = /* GraphQL */ `
  subscription OnUpdateUser {
    onUpdateUser {
      id
      username
      email
      avatarKey
      description
      pushToken
      accountID
      userType
      createdAt
      updatedAt
      _version
      _deleted
      _lastChangedAt
    }
  }
`;
export const onDeleteUser = /* GraphQL */ `
  subscription OnDeleteUser {
    onDeleteUser {
      id
      username
      email
      avatarKey
      description
      pushToken
      accountID
      userType
      createdAt
      updatedAt
      _version
      _deleted
      _lastChangedAt
    }
  }
`;
export const onCreateContact = /* GraphQL */ `
  subscription OnCreateContact {
    onCreateContact {
      id
      name
      status
      title
      email
      phone
      accountID
      createdAt
      updatedAt
      _version
      _deleted
      _lastChangedAt
    }
  }
`;
export const onUpdateContact = /* GraphQL */ `
  subscription OnUpdateContact {
    onUpdateContact {
      id
      name
      status
      title
      email
      phone
      accountID
      createdAt
      updatedAt
      _version
      _deleted
      _lastChangedAt
    }
  }
`;
export const onDeleteContact = /* GraphQL */ `
  subscription OnDeleteContact {
    onDeleteContact {
      id
      name
      status
      title
      email
      phone
      accountID
      createdAt
      updatedAt
      _version
      _deleted
      _lastChangedAt
    }
  }
`;
export const onCreateLocation = /* GraphQL */ `
  subscription OnCreateLocation {
    onCreateLocation {
      id
      value
      type
      parentID
      parentHierarchy
      parentName
      accountID
      createdAt
      updatedAt
      _version
      _deleted
      _lastChangedAt
    }
  }
`;
export const onUpdateLocation = /* GraphQL */ `
  subscription OnUpdateLocation {
    onUpdateLocation {
      id
      value
      type
      parentID
      parentHierarchy
      parentName
      accountID
      createdAt
      updatedAt
      _version
      _deleted
      _lastChangedAt
    }
  }
`;
export const onDeleteLocation = /* GraphQL */ `
  subscription OnDeleteLocation {
    onDeleteLocation {
      id
      value
      type
      parentID
      parentHierarchy
      parentName
      accountID
      createdAt
      updatedAt
      _version
      _deleted
      _lastChangedAt
    }
  }
`;
export const onCreateDevice = /* GraphQL */ `
  subscription OnCreateDevice {
    onCreateDevice {
      id
      udi
      parentHierarchy
      accountID
      mode
      cartridgeLevel
      clo2
      lastShotSize
      temperature
      humidity
      barometricPressure
      metadata {
        id
        name
        udi
        status
        type
        model
        externalReferences
        parentHierarchy
        deviceId
        device {
          id
          udi
          parentHierarchy
          accountID
          mode
          cartridgeLevel
          clo2
          lastShotSize
          temperature
          humidity
          barometricPressure
          metadata {
            id
            name
            udi
            status
            type
            model
            externalReferences
            parentHierarchy
            deviceId
            device {
              id
              udi
              parentHierarchy
              accountID
              mode
              cartridgeLevel
              clo2
              lastShotSize
              temperature
              humidity
              barometricPressure
              metadata {
                id
                name
                udi
                status
                type
                model
                externalReferences
                parentHierarchy
                deviceId
                device {
                  id
                  udi
                  parentHierarchy
                  accountID
                  mode
                  cartridgeLevel
                  clo2
                  lastShotSize
                  temperature
                  humidity
                  barometricPressure
                  metadata {
                    id
                    name
                    udi
                    status
                    type
                    model
                    externalReferences
                    parentHierarchy
                    deviceId
                    locationId
                    accountID
                    createdAt
                    updatedAt
                    _version
                    _deleted
                    _lastChangedAt
                  }
                  commsVersion
                  controllerVersion
                  createdAt
                  updatedAt
                  _version
                  _deleted
                  _lastChangedAt
                  deviceMetadataId
                }
                locationId
                location {
                  id
                  value
                  type
                  parentID
                  parentHierarchy
                  parentName
                  accountID
                  createdAt
                  updatedAt
                  _version
                  _deleted
                  _lastChangedAt
                }
                accountID
                createdAt
                updatedAt
                _version
                _deleted
                _lastChangedAt
              }
              commsVersion
              controllerVersion
              createdAt
              updatedAt
              _version
              _deleted
              _lastChangedAt
              deviceMetadataId
            }
            locationId
            location {
              id
              value
              type
              parentID
              parentHierarchy
              parentName
              accountID
              createdAt
              updatedAt
              _version
              _deleted
              _lastChangedAt
            }
            accountID
            createdAt
            updatedAt
            _version
            _deleted
            _lastChangedAt
          }
          commsVersion
          controllerVersion
          createdAt
          updatedAt
          _version
          _deleted
          _lastChangedAt
          deviceMetadataId
        }
        locationId
        location {
          id
          value
          type
          parentID
          parentHierarchy
          parentName
          accountID
          createdAt
          updatedAt
          _version
          _deleted
          _lastChangedAt
        }
        accountID
        createdAt
        updatedAt
        _version
        _deleted
        _lastChangedAt
      }
      commsVersion
      controllerVersion
      createdAt
      updatedAt
      _version
      _deleted
      _lastChangedAt
      deviceMetadataId
    }
  }
`;
export const onUpdateDevice = /* GraphQL */ `
  subscription OnUpdateDevice {
    onUpdateDevice {
      id
      udi
      parentHierarchy
      accountID
      mode
      cartridgeLevel
      clo2
      lastShotSize
      temperature
      humidity
      barometricPressure
      metadata {
        id
        name
        udi
        status
        type
        model
        externalReferences
        parentHierarchy
        deviceId
        device {
          id
          udi
          parentHierarchy
          accountID
          mode
          cartridgeLevel
          clo2
          lastShotSize
          temperature
          humidity
          barometricPressure
          metadata {
            id
            name
            udi
            status
            type
            model
            externalReferences
            parentHierarchy
            deviceId
            device {
              id
              udi
              parentHierarchy
              accountID
              mode
              cartridgeLevel
              clo2
              lastShotSize
              temperature
              humidity
              barometricPressure
              metadata {
                id
                name
                udi
                status
                type
                model
                externalReferences
                parentHierarchy
                deviceId
                device {
                  id
                  udi
                  parentHierarchy
                  accountID
                  mode
                  cartridgeLevel
                  clo2
                  lastShotSize
                  temperature
                  humidity
                  barometricPressure
                  metadata {
                    id
                    name
                    udi
                    status
                    type
                    model
                    externalReferences
                    parentHierarchy
                    deviceId
                    locationId
                    accountID
                    createdAt
                    updatedAt
                    _version
                    _deleted
                    _lastChangedAt
                  }
                  commsVersion
                  controllerVersion
                  createdAt
                  updatedAt
                  _version
                  _deleted
                  _lastChangedAt
                  deviceMetadataId
                }
                locationId
                location {
                  id
                  value
                  type
                  parentID
                  parentHierarchy
                  parentName
                  accountID
                  createdAt
                  updatedAt
                  _version
                  _deleted
                  _lastChangedAt
                }
                accountID
                createdAt
                updatedAt
                _version
                _deleted
                _lastChangedAt
              }
              commsVersion
              controllerVersion
              createdAt
              updatedAt
              _version
              _deleted
              _lastChangedAt
              deviceMetadataId
            }
            locationId
            location {
              id
              value
              type
              parentID
              parentHierarchy
              parentName
              accountID
              createdAt
              updatedAt
              _version
              _deleted
              _lastChangedAt
            }
            accountID
            createdAt
            updatedAt
            _version
            _deleted
            _lastChangedAt
          }
          commsVersion
          controllerVersion
          createdAt
          updatedAt
          _version
          _deleted
          _lastChangedAt
          deviceMetadataId
        }
        locationId
        location {
          id
          value
          type
          parentID
          parentHierarchy
          parentName
          accountID
          createdAt
          updatedAt
          _version
          _deleted
          _lastChangedAt
        }
        accountID
        createdAt
        updatedAt
        _version
        _deleted
        _lastChangedAt
      }
      commsVersion
      controllerVersion
      createdAt
      updatedAt
      _version
      _deleted
      _lastChangedAt
      deviceMetadataId
    }
  }
`;
export const onDeleteDevice = /* GraphQL */ `
  subscription OnDeleteDevice {
    onDeleteDevice {
      id
      udi
      parentHierarchy
      accountID
      mode
      cartridgeLevel
      clo2
      lastShotSize
      temperature
      humidity
      barometricPressure
      metadata {
        id
        name
        udi
        status
        type
        model
        externalReferences
        parentHierarchy
        deviceId
        device {
          id
          udi
          parentHierarchy
          accountID
          mode
          cartridgeLevel
          clo2
          lastShotSize
          temperature
          humidity
          barometricPressure
          metadata {
            id
            name
            udi
            status
            type
            model
            externalReferences
            parentHierarchy
            deviceId
            device {
              id
              udi
              parentHierarchy
              accountID
              mode
              cartridgeLevel
              clo2
              lastShotSize
              temperature
              humidity
              barometricPressure
              metadata {
                id
                name
                udi
                status
                type
                model
                externalReferences
                parentHierarchy
                deviceId
                device {
                  id
                  udi
                  parentHierarchy
                  accountID
                  mode
                  cartridgeLevel
                  clo2
                  lastShotSize
                  temperature
                  humidity
                  barometricPressure
                  metadata {
                    id
                    name
                    udi
                    status
                    type
                    model
                    externalReferences
                    parentHierarchy
                    deviceId
                    locationId
                    accountID
                    createdAt
                    updatedAt
                    _version
                    _deleted
                    _lastChangedAt
                  }
                  commsVersion
                  controllerVersion
                  createdAt
                  updatedAt
                  _version
                  _deleted
                  _lastChangedAt
                  deviceMetadataId
                }
                locationId
                location {
                  id
                  value
                  type
                  parentID
                  parentHierarchy
                  parentName
                  accountID
                  createdAt
                  updatedAt
                  _version
                  _deleted
                  _lastChangedAt
                }
                accountID
                createdAt
                updatedAt
                _version
                _deleted
                _lastChangedAt
              }
              commsVersion
              controllerVersion
              createdAt
              updatedAt
              _version
              _deleted
              _lastChangedAt
              deviceMetadataId
            }
            locationId
            location {
              id
              value
              type
              parentID
              parentHierarchy
              parentName
              accountID
              createdAt
              updatedAt
              _version
              _deleted
              _lastChangedAt
            }
            accountID
            createdAt
            updatedAt
            _version
            _deleted
            _lastChangedAt
          }
          commsVersion
          controllerVersion
          createdAt
          updatedAt
          _version
          _deleted
          _lastChangedAt
          deviceMetadataId
        }
        locationId
        location {
          id
          value
          type
          parentID
          parentHierarchy
          parentName
          accountID
          createdAt
          updatedAt
          _version
          _deleted
          _lastChangedAt
        }
        accountID
        createdAt
        updatedAt
        _version
        _deleted
        _lastChangedAt
      }
      commsVersion
      controllerVersion
      createdAt
      updatedAt
      _version
      _deleted
      _lastChangedAt
      deviceMetadataId
    }
  }
`;
export const onCreateDeviceMetadata = /* GraphQL */ `
  subscription OnCreateDeviceMetadata {
    onCreateDeviceMetadata {
      id
      name
      udi
      status
      type
      model
      externalReferences
      parentHierarchy
      deviceId
      device {
        id
        udi
        parentHierarchy
        accountID
        mode
        cartridgeLevel
        clo2
        lastShotSize
        temperature
        humidity
        barometricPressure
        metadata {
          id
          name
          udi
          status
          type
          model
          externalReferences
          parentHierarchy
          deviceId
          device {
            id
            udi
            parentHierarchy
            accountID
            mode
            cartridgeLevel
            clo2
            lastShotSize
            temperature
            humidity
            barometricPressure
            metadata {
              id
              name
              udi
              status
              type
              model
              externalReferences
              parentHierarchy
              deviceId
              device {
                id
                udi
                parentHierarchy
                accountID
                mode
                cartridgeLevel
                clo2
                lastShotSize
                temperature
                humidity
                barometricPressure
                metadata {
                  id
                  name
                  udi
                  status
                  type
                  model
                  externalReferences
                  parentHierarchy
                  deviceId
                  device {
                    id
                    udi
                    parentHierarchy
                    accountID
                    mode
                    cartridgeLevel
                    clo2
                    lastShotSize
                    temperature
                    humidity
                    barometricPressure
                    commsVersion
                    controllerVersion
                    createdAt
                    updatedAt
                    _version
                    _deleted
                    _lastChangedAt
                    deviceMetadataId
                  }
                  locationId
                  location {
                    id
                    value
                    type
                    parentID
                    parentHierarchy
                    parentName
                    accountID
                    createdAt
                    updatedAt
                    _version
                    _deleted
                    _lastChangedAt
                  }
                  accountID
                  createdAt
                  updatedAt
                  _version
                  _deleted
                  _lastChangedAt
                }
                commsVersion
                controllerVersion
                createdAt
                updatedAt
                _version
                _deleted
                _lastChangedAt
                deviceMetadataId
              }
              locationId
              location {
                id
                value
                type
                parentID
                parentHierarchy
                parentName
                accountID
                createdAt
                updatedAt
                _version
                _deleted
                _lastChangedAt
              }
              accountID
              createdAt
              updatedAt
              _version
              _deleted
              _lastChangedAt
            }
            commsVersion
            controllerVersion
            createdAt
            updatedAt
            _version
            _deleted
            _lastChangedAt
            deviceMetadataId
          }
          locationId
          location {
            id
            value
            type
            parentID
            parentHierarchy
            parentName
            accountID
            createdAt
            updatedAt
            _version
            _deleted
            _lastChangedAt
          }
          accountID
          createdAt
          updatedAt
          _version
          _deleted
          _lastChangedAt
        }
        commsVersion
        controllerVersion
        createdAt
        updatedAt
        _version
        _deleted
        _lastChangedAt
        deviceMetadataId
      }
      locationId
      location {
        id
        value
        type
        parentID
        parentHierarchy
        parentName
        accountID
        createdAt
        updatedAt
        _version
        _deleted
        _lastChangedAt
      }
      accountID
      createdAt
      updatedAt
      _version
      _deleted
      _lastChangedAt
    }
  }
`;
export const onUpdateDeviceMetadata = /* GraphQL */ `
  subscription OnUpdateDeviceMetadata {
    onUpdateDeviceMetadata {
      id
      name
      udi
      status
      type
      model
      externalReferences
      parentHierarchy
      deviceId
      device {
        id
        udi
        parentHierarchy
        accountID
        mode
        cartridgeLevel
        clo2
        lastShotSize
        temperature
        humidity
        barometricPressure
        metadata {
          id
          name
          udi
          status
          type
          model
          externalReferences
          parentHierarchy
          deviceId
          device {
            id
            udi
            parentHierarchy
            accountID
            mode
            cartridgeLevel
            clo2
            lastShotSize
            temperature
            humidity
            barometricPressure
            metadata {
              id
              name
              udi
              status
              type
              model
              externalReferences
              parentHierarchy
              deviceId
              device {
                id
                udi
                parentHierarchy
                accountID
                mode
                cartridgeLevel
                clo2
                lastShotSize
                temperature
                humidity
                barometricPressure
                metadata {
                  id
                  name
                  udi
                  status
                  type
                  model
                  externalReferences
                  parentHierarchy
                  deviceId
                  device {
                    id
                    udi
                    parentHierarchy
                    accountID
                    mode
                    cartridgeLevel
                    clo2
                    lastShotSize
                    temperature
                    humidity
                    barometricPressure
                    commsVersion
                    controllerVersion
                    createdAt
                    updatedAt
                    _version
                    _deleted
                    _lastChangedAt
                    deviceMetadataId
                  }
                  locationId
                  location {
                    id
                    value
                    type
                    parentID
                    parentHierarchy
                    parentName
                    accountID
                    createdAt
                    updatedAt
                    _version
                    _deleted
                    _lastChangedAt
                  }
                  accountID
                  createdAt
                  updatedAt
                  _version
                  _deleted
                  _lastChangedAt
                }
                commsVersion
                controllerVersion
                createdAt
                updatedAt
                _version
                _deleted
                _lastChangedAt
                deviceMetadataId
              }
              locationId
              location {
                id
                value
                type
                parentID
                parentHierarchy
                parentName
                accountID
                createdAt
                updatedAt
                _version
                _deleted
                _lastChangedAt
              }
              accountID
              createdAt
              updatedAt
              _version
              _deleted
              _lastChangedAt
            }
            commsVersion
            controllerVersion
            createdAt
            updatedAt
            _version
            _deleted
            _lastChangedAt
            deviceMetadataId
          }
          locationId
          location {
            id
            value
            type
            parentID
            parentHierarchy
            parentName
            accountID
            createdAt
            updatedAt
            _version
            _deleted
            _lastChangedAt
          }
          accountID
          createdAt
          updatedAt
          _version
          _deleted
          _lastChangedAt
        }
        commsVersion
        controllerVersion
        createdAt
        updatedAt
        _version
        _deleted
        _lastChangedAt
        deviceMetadataId
      }
      locationId
      location {
        id
        value
        type
        parentID
        parentHierarchy
        parentName
        accountID
        createdAt
        updatedAt
        _version
        _deleted
        _lastChangedAt
      }
      accountID
      createdAt
      updatedAt
      _version
      _deleted
      _lastChangedAt
    }
  }
`;
export const onDeleteDeviceMetadata = /* GraphQL */ `
  subscription OnDeleteDeviceMetadata {
    onDeleteDeviceMetadata {
      id
      name
      udi
      status
      type
      model
      externalReferences
      parentHierarchy
      deviceId
      device {
        id
        udi
        parentHierarchy
        accountID
        mode
        cartridgeLevel
        clo2
        lastShotSize
        temperature
        humidity
        barometricPressure
        metadata {
          id
          name
          udi
          status
          type
          model
          externalReferences
          parentHierarchy
          deviceId
          device {
            id
            udi
            parentHierarchy
            accountID
            mode
            cartridgeLevel
            clo2
            lastShotSize
            temperature
            humidity
            barometricPressure
            metadata {
              id
              name
              udi
              status
              type
              model
              externalReferences
              parentHierarchy
              deviceId
              device {
                id
                udi
                parentHierarchy
                accountID
                mode
                cartridgeLevel
                clo2
                lastShotSize
                temperature
                humidity
                barometricPressure
                metadata {
                  id
                  name
                  udi
                  status
                  type
                  model
                  externalReferences
                  parentHierarchy
                  deviceId
                  device {
                    id
                    udi
                    parentHierarchy
                    accountID
                    mode
                    cartridgeLevel
                    clo2
                    lastShotSize
                    temperature
                    humidity
                    barometricPressure
                    commsVersion
                    controllerVersion
                    createdAt
                    updatedAt
                    _version
                    _deleted
                    _lastChangedAt
                    deviceMetadataId
                  }
                  locationId
                  location {
                    id
                    value
                    type
                    parentID
                    parentHierarchy
                    parentName
                    accountID
                    createdAt
                    updatedAt
                    _version
                    _deleted
                    _lastChangedAt
                  }
                  accountID
                  createdAt
                  updatedAt
                  _version
                  _deleted
                  _lastChangedAt
                }
                commsVersion
                controllerVersion
                createdAt
                updatedAt
                _version
                _deleted
                _lastChangedAt
                deviceMetadataId
              }
              locationId
              location {
                id
                value
                type
                parentID
                parentHierarchy
                parentName
                accountID
                createdAt
                updatedAt
                _version
                _deleted
                _lastChangedAt
              }
              accountID
              createdAt
              updatedAt
              _version
              _deleted
              _lastChangedAt
            }
            commsVersion
            controllerVersion
            createdAt
            updatedAt
            _version
            _deleted
            _lastChangedAt
            deviceMetadataId
          }
          locationId
          location {
            id
            value
            type
            parentID
            parentHierarchy
            parentName
            accountID
            createdAt
            updatedAt
            _version
            _deleted
            _lastChangedAt
          }
          accountID
          createdAt
          updatedAt
          _version
          _deleted
          _lastChangedAt
        }
        commsVersion
        controllerVersion
        createdAt
        updatedAt
        _version
        _deleted
        _lastChangedAt
        deviceMetadataId
      }
      locationId
      location {
        id
        value
        type
        parentID
        parentHierarchy
        parentName
        accountID
        createdAt
        updatedAt
        _version
        _deleted
        _lastChangedAt
      }
      accountID
      createdAt
      updatedAt
      _version
      _deleted
      _lastChangedAt
    }
  }
`;
export const onCreateDeviceTelemetry = /* GraphQL */ `
  subscription OnCreateDeviceTelemetry {
    onCreateDeviceTelemetry {
      id
      clo2 {
        label
        value
        uom
        icon
      }
      temperature {
        label
        value
        uom
        icon
      }
      humidity {
        label
        value
        uom
        icon
      }
      barometricPressure {
        label
        value
        uom
        icon
      }
      generated
      lastShotSize {
        label
        value
        uom
        icon
      }
      deviceId
      device {
        id
        udi
        parentHierarchy
        accountID
        mode
        cartridgeLevel
        clo2
        lastShotSize
        temperature
        humidity
        barometricPressure
        metadata {
          id
          name
          udi
          status
          type
          model
          externalReferences
          parentHierarchy
          deviceId
          device {
            id
            udi
            parentHierarchy
            accountID
            mode
            cartridgeLevel
            clo2
            lastShotSize
            temperature
            humidity
            barometricPressure
            metadata {
              id
              name
              udi
              status
              type
              model
              externalReferences
              parentHierarchy
              deviceId
              device {
                id
                udi
                parentHierarchy
                accountID
                mode
                cartridgeLevel
                clo2
                lastShotSize
                temperature
                humidity
                barometricPressure
                metadata {
                  id
                  name
                  udi
                  status
                  type
                  model
                  externalReferences
                  parentHierarchy
                  deviceId
                  device {
                    id
                    udi
                    parentHierarchy
                    accountID
                    mode
                    cartridgeLevel
                    clo2
                    lastShotSize
                    temperature
                    humidity
                    barometricPressure
                    commsVersion
                    controllerVersion
                    createdAt
                    updatedAt
                    _version
                    _deleted
                    _lastChangedAt
                    deviceMetadataId
                  }
                  locationId
                  location {
                    id
                    value
                    type
                    parentID
                    parentHierarchy
                    parentName
                    accountID
                    createdAt
                    updatedAt
                    _version
                    _deleted
                    _lastChangedAt
                  }
                  accountID
                  createdAt
                  updatedAt
                  _version
                  _deleted
                  _lastChangedAt
                }
                commsVersion
                controllerVersion
                createdAt
                updatedAt
                _version
                _deleted
                _lastChangedAt
                deviceMetadataId
              }
              locationId
              location {
                id
                value
                type
                parentID
                parentHierarchy
                parentName
                accountID
                createdAt
                updatedAt
                _version
                _deleted
                _lastChangedAt
              }
              accountID
              createdAt
              updatedAt
              _version
              _deleted
              _lastChangedAt
            }
            commsVersion
            controllerVersion
            createdAt
            updatedAt
            _version
            _deleted
            _lastChangedAt
            deviceMetadataId
          }
          locationId
          location {
            id
            value
            type
            parentID
            parentHierarchy
            parentName
            accountID
            createdAt
            updatedAt
            _version
            _deleted
            _lastChangedAt
          }
          accountID
          createdAt
          updatedAt
          _version
          _deleted
          _lastChangedAt
        }
        commsVersion
        controllerVersion
        createdAt
        updatedAt
        _version
        _deleted
        _lastChangedAt
        deviceMetadataId
      }
      eventDate
      rawEvent
      accountID
      createdAt
      updatedAt
      _version
      _deleted
      _lastChangedAt
    }
  }
`;
export const onUpdateDeviceTelemetry = /* GraphQL */ `
  subscription OnUpdateDeviceTelemetry {
    onUpdateDeviceTelemetry {
      id
      clo2 {
        label
        value
        uom
        icon
      }
      temperature {
        label
        value
        uom
        icon
      }
      humidity {
        label
        value
        uom
        icon
      }
      barometricPressure {
        label
        value
        uom
        icon
      }
      generated
      lastShotSize {
        label
        value
        uom
        icon
      }
      deviceId
      device {
        id
        udi
        parentHierarchy
        accountID
        mode
        cartridgeLevel
        clo2
        lastShotSize
        temperature
        humidity
        barometricPressure
        metadata {
          id
          name
          udi
          status
          type
          model
          externalReferences
          parentHierarchy
          deviceId
          device {
            id
            udi
            parentHierarchy
            accountID
            mode
            cartridgeLevel
            clo2
            lastShotSize
            temperature
            humidity
            barometricPressure
            metadata {
              id
              name
              udi
              status
              type
              model
              externalReferences
              parentHierarchy
              deviceId
              device {
                id
                udi
                parentHierarchy
                accountID
                mode
                cartridgeLevel
                clo2
                lastShotSize
                temperature
                humidity
                barometricPressure
                metadata {
                  id
                  name
                  udi
                  status
                  type
                  model
                  externalReferences
                  parentHierarchy
                  deviceId
                  device {
                    id
                    udi
                    parentHierarchy
                    accountID
                    mode
                    cartridgeLevel
                    clo2
                    lastShotSize
                    temperature
                    humidity
                    barometricPressure
                    commsVersion
                    controllerVersion
                    createdAt
                    updatedAt
                    _version
                    _deleted
                    _lastChangedAt
                    deviceMetadataId
                  }
                  locationId
                  location {
                    id
                    value
                    type
                    parentID
                    parentHierarchy
                    parentName
                    accountID
                    createdAt
                    updatedAt
                    _version
                    _deleted
                    _lastChangedAt
                  }
                  accountID
                  createdAt
                  updatedAt
                  _version
                  _deleted
                  _lastChangedAt
                }
                commsVersion
                controllerVersion
                createdAt
                updatedAt
                _version
                _deleted
                _lastChangedAt
                deviceMetadataId
              }
              locationId
              location {
                id
                value
                type
                parentID
                parentHierarchy
                parentName
                accountID
                createdAt
                updatedAt
                _version
                _deleted
                _lastChangedAt
              }
              accountID
              createdAt
              updatedAt
              _version
              _deleted
              _lastChangedAt
            }
            commsVersion
            controllerVersion
            createdAt
            updatedAt
            _version
            _deleted
            _lastChangedAt
            deviceMetadataId
          }
          locationId
          location {
            id
            value
            type
            parentID
            parentHierarchy
            parentName
            accountID
            createdAt
            updatedAt
            _version
            _deleted
            _lastChangedAt
          }
          accountID
          createdAt
          updatedAt
          _version
          _deleted
          _lastChangedAt
        }
        commsVersion
        controllerVersion
        createdAt
        updatedAt
        _version
        _deleted
        _lastChangedAt
        deviceMetadataId
      }
      eventDate
      rawEvent
      accountID
      createdAt
      updatedAt
      _version
      _deleted
      _lastChangedAt
    }
  }
`;
export const onDeleteDeviceTelemetry = /* GraphQL */ `
  subscription OnDeleteDeviceTelemetry {
    onDeleteDeviceTelemetry {
      id
      clo2 {
        label
        value
        uom
        icon
      }
      temperature {
        label
        value
        uom
        icon
      }
      humidity {
        label
        value
        uom
        icon
      }
      barometricPressure {
        label
        value
        uom
        icon
      }
      generated
      lastShotSize {
        label
        value
        uom
        icon
      }
      deviceId
      device {
        id
        udi
        parentHierarchy
        accountID
        mode
        cartridgeLevel
        clo2
        lastShotSize
        temperature
        humidity
        barometricPressure
        metadata {
          id
          name
          udi
          status
          type
          model
          externalReferences
          parentHierarchy
          deviceId
          device {
            id
            udi
            parentHierarchy
            accountID
            mode
            cartridgeLevel
            clo2
            lastShotSize
            temperature
            humidity
            barometricPressure
            metadata {
              id
              name
              udi
              status
              type
              model
              externalReferences
              parentHierarchy
              deviceId
              device {
                id
                udi
                parentHierarchy
                accountID
                mode
                cartridgeLevel
                clo2
                lastShotSize
                temperature
                humidity
                barometricPressure
                metadata {
                  id
                  name
                  udi
                  status
                  type
                  model
                  externalReferences
                  parentHierarchy
                  deviceId
                  device {
                    id
                    udi
                    parentHierarchy
                    accountID
                    mode
                    cartridgeLevel
                    clo2
                    lastShotSize
                    temperature
                    humidity
                    barometricPressure
                    commsVersion
                    controllerVersion
                    createdAt
                    updatedAt
                    _version
                    _deleted
                    _lastChangedAt
                    deviceMetadataId
                  }
                  locationId
                  location {
                    id
                    value
                    type
                    parentID
                    parentHierarchy
                    parentName
                    accountID
                    createdAt
                    updatedAt
                    _version
                    _deleted
                    _lastChangedAt
                  }
                  accountID
                  createdAt
                  updatedAt
                  _version
                  _deleted
                  _lastChangedAt
                }
                commsVersion
                controllerVersion
                createdAt
                updatedAt
                _version
                _deleted
                _lastChangedAt
                deviceMetadataId
              }
              locationId
              location {
                id
                value
                type
                parentID
                parentHierarchy
                parentName
                accountID
                createdAt
                updatedAt
                _version
                _deleted
                _lastChangedAt
              }
              accountID
              createdAt
              updatedAt
              _version
              _deleted
              _lastChangedAt
            }
            commsVersion
            controllerVersion
            createdAt
            updatedAt
            _version
            _deleted
            _lastChangedAt
            deviceMetadataId
          }
          locationId
          location {
            id
            value
            type
            parentID
            parentHierarchy
            parentName
            accountID
            createdAt
            updatedAt
            _version
            _deleted
            _lastChangedAt
          }
          accountID
          createdAt
          updatedAt
          _version
          _deleted
          _lastChangedAt
        }
        commsVersion
        controllerVersion
        createdAt
        updatedAt
        _version
        _deleted
        _lastChangedAt
        deviceMetadataId
      }
      eventDate
      rawEvent
      accountID
      createdAt
      updatedAt
      _version
      _deleted
      _lastChangedAt
    }
  }
`;
export const onCreateDeviceConfiguration = /* GraphQL */ `
  subscription OnCreateDeviceConfiguration {
    onCreateDeviceConfiguration {
      id
      rawEvent
      eventDate
      deviceId
      device {
        id
        udi
        parentHierarchy
        accountID
        mode
        cartridgeLevel
        clo2
        lastShotSize
        temperature
        humidity
        barometricPressure
        metadata {
          id
          name
          udi
          status
          type
          model
          externalReferences
          parentHierarchy
          deviceId
          device {
            id
            udi
            parentHierarchy
            accountID
            mode
            cartridgeLevel
            clo2
            lastShotSize
            temperature
            humidity
            barometricPressure
            metadata {
              id
              name
              udi
              status
              type
              model
              externalReferences
              parentHierarchy
              deviceId
              device {
                id
                udi
                parentHierarchy
                accountID
                mode
                cartridgeLevel
                clo2
                lastShotSize
                temperature
                humidity
                barometricPressure
                metadata {
                  id
                  name
                  udi
                  status
                  type
                  model
                  externalReferences
                  parentHierarchy
                  deviceId
                  device {
                    id
                    udi
                    parentHierarchy
                    accountID
                    mode
                    cartridgeLevel
                    clo2
                    lastShotSize
                    temperature
                    humidity
                    barometricPressure
                    commsVersion
                    controllerVersion
                    createdAt
                    updatedAt
                    _version
                    _deleted
                    _lastChangedAt
                    deviceMetadataId
                  }
                  locationId
                  location {
                    id
                    value
                    type
                    parentID
                    parentHierarchy
                    parentName
                    accountID
                    createdAt
                    updatedAt
                    _version
                    _deleted
                    _lastChangedAt
                  }
                  accountID
                  createdAt
                  updatedAt
                  _version
                  _deleted
                  _lastChangedAt
                }
                commsVersion
                controllerVersion
                createdAt
                updatedAt
                _version
                _deleted
                _lastChangedAt
                deviceMetadataId
              }
              locationId
              location {
                id
                value
                type
                parentID
                parentHierarchy
                parentName
                accountID
                createdAt
                updatedAt
                _version
                _deleted
                _lastChangedAt
              }
              accountID
              createdAt
              updatedAt
              _version
              _deleted
              _lastChangedAt
            }
            commsVersion
            controllerVersion
            createdAt
            updatedAt
            _version
            _deleted
            _lastChangedAt
            deviceMetadataId
          }
          locationId
          location {
            id
            value
            type
            parentID
            parentHierarchy
            parentName
            accountID
            createdAt
            updatedAt
            _version
            _deleted
            _lastChangedAt
          }
          accountID
          createdAt
          updatedAt
          _version
          _deleted
          _lastChangedAt
        }
        commsVersion
        controllerVersion
        createdAt
        updatedAt
        _version
        _deleted
        _lastChangedAt
        deviceMetadataId
      }
      telemetryPublishRateMs
      parameterPollingRateMs
      commsVersion
      controllerVersion
      accountID
      createdAt
      updatedAt
      _version
      _deleted
      _lastChangedAt
    }
  }
`;
export const onUpdateDeviceConfiguration = /* GraphQL */ `
  subscription OnUpdateDeviceConfiguration {
    onUpdateDeviceConfiguration {
      id
      rawEvent
      eventDate
      deviceId
      device {
        id
        udi
        parentHierarchy
        accountID
        mode
        cartridgeLevel
        clo2
        lastShotSize
        temperature
        humidity
        barometricPressure
        metadata {
          id
          name
          udi
          status
          type
          model
          externalReferences
          parentHierarchy
          deviceId
          device {
            id
            udi
            parentHierarchy
            accountID
            mode
            cartridgeLevel
            clo2
            lastShotSize
            temperature
            humidity
            barometricPressure
            metadata {
              id
              name
              udi
              status
              type
              model
              externalReferences
              parentHierarchy
              deviceId
              device {
                id
                udi
                parentHierarchy
                accountID
                mode
                cartridgeLevel
                clo2
                lastShotSize
                temperature
                humidity
                barometricPressure
                metadata {
                  id
                  name
                  udi
                  status
                  type
                  model
                  externalReferences
                  parentHierarchy
                  deviceId
                  device {
                    id
                    udi
                    parentHierarchy
                    accountID
                    mode
                    cartridgeLevel
                    clo2
                    lastShotSize
                    temperature
                    humidity
                    barometricPressure
                    commsVersion
                    controllerVersion
                    createdAt
                    updatedAt
                    _version
                    _deleted
                    _lastChangedAt
                    deviceMetadataId
                  }
                  locationId
                  location {
                    id
                    value
                    type
                    parentID
                    parentHierarchy
                    parentName
                    accountID
                    createdAt
                    updatedAt
                    _version
                    _deleted
                    _lastChangedAt
                  }
                  accountID
                  createdAt
                  updatedAt
                  _version
                  _deleted
                  _lastChangedAt
                }
                commsVersion
                controllerVersion
                createdAt
                updatedAt
                _version
                _deleted
                _lastChangedAt
                deviceMetadataId
              }
              locationId
              location {
                id
                value
                type
                parentID
                parentHierarchy
                parentName
                accountID
                createdAt
                updatedAt
                _version
                _deleted
                _lastChangedAt
              }
              accountID
              createdAt
              updatedAt
              _version
              _deleted
              _lastChangedAt
            }
            commsVersion
            controllerVersion
            createdAt
            updatedAt
            _version
            _deleted
            _lastChangedAt
            deviceMetadataId
          }
          locationId
          location {
            id
            value
            type
            parentID
            parentHierarchy
            parentName
            accountID
            createdAt
            updatedAt
            _version
            _deleted
            _lastChangedAt
          }
          accountID
          createdAt
          updatedAt
          _version
          _deleted
          _lastChangedAt
        }
        commsVersion
        controllerVersion
        createdAt
        updatedAt
        _version
        _deleted
        _lastChangedAt
        deviceMetadataId
      }
      telemetryPublishRateMs
      parameterPollingRateMs
      commsVersion
      controllerVersion
      accountID
      createdAt
      updatedAt
      _version
      _deleted
      _lastChangedAt
    }
  }
`;
export const onDeleteDeviceConfiguration = /* GraphQL */ `
  subscription OnDeleteDeviceConfiguration {
    onDeleteDeviceConfiguration {
      id
      rawEvent
      eventDate
      deviceId
      device {
        id
        udi
        parentHierarchy
        accountID
        mode
        cartridgeLevel
        clo2
        lastShotSize
        temperature
        humidity
        barometricPressure
        metadata {
          id
          name
          udi
          status
          type
          model
          externalReferences
          parentHierarchy
          deviceId
          device {
            id
            udi
            parentHierarchy
            accountID
            mode
            cartridgeLevel
            clo2
            lastShotSize
            temperature
            humidity
            barometricPressure
            metadata {
              id
              name
              udi
              status
              type
              model
              externalReferences
              parentHierarchy
              deviceId
              device {
                id
                udi
                parentHierarchy
                accountID
                mode
                cartridgeLevel
                clo2
                lastShotSize
                temperature
                humidity
                barometricPressure
                metadata {
                  id
                  name
                  udi
                  status
                  type
                  model
                  externalReferences
                  parentHierarchy
                  deviceId
                  device {
                    id
                    udi
                    parentHierarchy
                    accountID
                    mode
                    cartridgeLevel
                    clo2
                    lastShotSize
                    temperature
                    humidity
                    barometricPressure
                    commsVersion
                    controllerVersion
                    createdAt
                    updatedAt
                    _version
                    _deleted
                    _lastChangedAt
                    deviceMetadataId
                  }
                  locationId
                  location {
                    id
                    value
                    type
                    parentID
                    parentHierarchy
                    parentName
                    accountID
                    createdAt
                    updatedAt
                    _version
                    _deleted
                    _lastChangedAt
                  }
                  accountID
                  createdAt
                  updatedAt
                  _version
                  _deleted
                  _lastChangedAt
                }
                commsVersion
                controllerVersion
                createdAt
                updatedAt
                _version
                _deleted
                _lastChangedAt
                deviceMetadataId
              }
              locationId
              location {
                id
                value
                type
                parentID
                parentHierarchy
                parentName
                accountID
                createdAt
                updatedAt
                _version
                _deleted
                _lastChangedAt
              }
              accountID
              createdAt
              updatedAt
              _version
              _deleted
              _lastChangedAt
            }
            commsVersion
            controllerVersion
            createdAt
            updatedAt
            _version
            _deleted
            _lastChangedAt
            deviceMetadataId
          }
          locationId
          location {
            id
            value
            type
            parentID
            parentHierarchy
            parentName
            accountID
            createdAt
            updatedAt
            _version
            _deleted
            _lastChangedAt
          }
          accountID
          createdAt
          updatedAt
          _version
          _deleted
          _lastChangedAt
        }
        commsVersion
        controllerVersion
        createdAt
        updatedAt
        _version
        _deleted
        _lastChangedAt
        deviceMetadataId
      }
      telemetryPublishRateMs
      parameterPollingRateMs
      commsVersion
      controllerVersion
      accountID
      createdAt
      updatedAt
      _version
      _deleted
      _lastChangedAt
    }
  }
`;
export const onCreateDeviceState = /* GraphQL */ `
  subscription OnCreateDeviceState {
    onCreateDeviceState {
      id
      mode
      cartridgeLevel {
        label
        value
        uom
        icon
      }
      deviceId
      device {
        id
        udi
        parentHierarchy
        accountID
        mode
        cartridgeLevel
        clo2
        lastShotSize
        temperature
        humidity
        barometricPressure
        metadata {
          id
          name
          udi
          status
          type
          model
          externalReferences
          parentHierarchy
          deviceId
          device {
            id
            udi
            parentHierarchy
            accountID
            mode
            cartridgeLevel
            clo2
            lastShotSize
            temperature
            humidity
            barometricPressure
            metadata {
              id
              name
              udi
              status
              type
              model
              externalReferences
              parentHierarchy
              deviceId
              device {
                id
                udi
                parentHierarchy
                accountID
                mode
                cartridgeLevel
                clo2
                lastShotSize
                temperature
                humidity
                barometricPressure
                metadata {
                  id
                  name
                  udi
                  status
                  type
                  model
                  externalReferences
                  parentHierarchy
                  deviceId
                  device {
                    id
                    udi
                    parentHierarchy
                    accountID
                    mode
                    cartridgeLevel
                    clo2
                    lastShotSize
                    temperature
                    humidity
                    barometricPressure
                    commsVersion
                    controllerVersion
                    createdAt
                    updatedAt
                    _version
                    _deleted
                    _lastChangedAt
                    deviceMetadataId
                  }
                  locationId
                  location {
                    id
                    value
                    type
                    parentID
                    parentHierarchy
                    parentName
                    accountID
                    createdAt
                    updatedAt
                    _version
                    _deleted
                    _lastChangedAt
                  }
                  accountID
                  createdAt
                  updatedAt
                  _version
                  _deleted
                  _lastChangedAt
                }
                commsVersion
                controllerVersion
                createdAt
                updatedAt
                _version
                _deleted
                _lastChangedAt
                deviceMetadataId
              }
              locationId
              location {
                id
                value
                type
                parentID
                parentHierarchy
                parentName
                accountID
                createdAt
                updatedAt
                _version
                _deleted
                _lastChangedAt
              }
              accountID
              createdAt
              updatedAt
              _version
              _deleted
              _lastChangedAt
            }
            commsVersion
            controllerVersion
            createdAt
            updatedAt
            _version
            _deleted
            _lastChangedAt
            deviceMetadataId
          }
          locationId
          location {
            id
            value
            type
            parentID
            parentHierarchy
            parentName
            accountID
            createdAt
            updatedAt
            _version
            _deleted
            _lastChangedAt
          }
          accountID
          createdAt
          updatedAt
          _version
          _deleted
          _lastChangedAt
        }
        commsVersion
        controllerVersion
        createdAt
        updatedAt
        _version
        _deleted
        _lastChangedAt
        deviceMetadataId
      }
      eventDate
      rawEvent
      accountID
      createdAt
      updatedAt
      _version
      _deleted
      _lastChangedAt
    }
  }
`;
export const onUpdateDeviceState = /* GraphQL */ `
  subscription OnUpdateDeviceState {
    onUpdateDeviceState {
      id
      mode
      cartridgeLevel {
        label
        value
        uom
        icon
      }
      deviceId
      device {
        id
        udi
        parentHierarchy
        accountID
        mode
        cartridgeLevel
        clo2
        lastShotSize
        temperature
        humidity
        barometricPressure
        metadata {
          id
          name
          udi
          status
          type
          model
          externalReferences
          parentHierarchy
          deviceId
          device {
            id
            udi
            parentHierarchy
            accountID
            mode
            cartridgeLevel
            clo2
            lastShotSize
            temperature
            humidity
            barometricPressure
            metadata {
              id
              name
              udi
              status
              type
              model
              externalReferences
              parentHierarchy
              deviceId
              device {
                id
                udi
                parentHierarchy
                accountID
                mode
                cartridgeLevel
                clo2
                lastShotSize
                temperature
                humidity
                barometricPressure
                metadata {
                  id
                  name
                  udi
                  status
                  type
                  model
                  externalReferences
                  parentHierarchy
                  deviceId
                  device {
                    id
                    udi
                    parentHierarchy
                    accountID
                    mode
                    cartridgeLevel
                    clo2
                    lastShotSize
                    temperature
                    humidity
                    barometricPressure
                    commsVersion
                    controllerVersion
                    createdAt
                    updatedAt
                    _version
                    _deleted
                    _lastChangedAt
                    deviceMetadataId
                  }
                  locationId
                  location {
                    id
                    value
                    type
                    parentID
                    parentHierarchy
                    parentName
                    accountID
                    createdAt
                    updatedAt
                    _version
                    _deleted
                    _lastChangedAt
                  }
                  accountID
                  createdAt
                  updatedAt
                  _version
                  _deleted
                  _lastChangedAt
                }
                commsVersion
                controllerVersion
                createdAt
                updatedAt
                _version
                _deleted
                _lastChangedAt
                deviceMetadataId
              }
              locationId
              location {
                id
                value
                type
                parentID
                parentHierarchy
                parentName
                accountID
                createdAt
                updatedAt
                _version
                _deleted
                _lastChangedAt
              }
              accountID
              createdAt
              updatedAt
              _version
              _deleted
              _lastChangedAt
            }
            commsVersion
            controllerVersion
            createdAt
            updatedAt
            _version
            _deleted
            _lastChangedAt
            deviceMetadataId
          }
          locationId
          location {
            id
            value
            type
            parentID
            parentHierarchy
            parentName
            accountID
            createdAt
            updatedAt
            _version
            _deleted
            _lastChangedAt
          }
          accountID
          createdAt
          updatedAt
          _version
          _deleted
          _lastChangedAt
        }
        commsVersion
        controllerVersion
        createdAt
        updatedAt
        _version
        _deleted
        _lastChangedAt
        deviceMetadataId
      }
      eventDate
      rawEvent
      accountID
      createdAt
      updatedAt
      _version
      _deleted
      _lastChangedAt
    }
  }
`;
export const onDeleteDeviceState = /* GraphQL */ `
  subscription OnDeleteDeviceState {
    onDeleteDeviceState {
      id
      mode
      cartridgeLevel {
        label
        value
        uom
        icon
      }
      deviceId
      device {
        id
        udi
        parentHierarchy
        accountID
        mode
        cartridgeLevel
        clo2
        lastShotSize
        temperature
        humidity
        barometricPressure
        metadata {
          id
          name
          udi
          status
          type
          model
          externalReferences
          parentHierarchy
          deviceId
          device {
            id
            udi
            parentHierarchy
            accountID
            mode
            cartridgeLevel
            clo2
            lastShotSize
            temperature
            humidity
            barometricPressure
            metadata {
              id
              name
              udi
              status
              type
              model
              externalReferences
              parentHierarchy
              deviceId
              device {
                id
                udi
                parentHierarchy
                accountID
                mode
                cartridgeLevel
                clo2
                lastShotSize
                temperature
                humidity
                barometricPressure
                metadata {
                  id
                  name
                  udi
                  status
                  type
                  model
                  externalReferences
                  parentHierarchy
                  deviceId
                  device {
                    id
                    udi
                    parentHierarchy
                    accountID
                    mode
                    cartridgeLevel
                    clo2
                    lastShotSize
                    temperature
                    humidity
                    barometricPressure
                    commsVersion
                    controllerVersion
                    createdAt
                    updatedAt
                    _version
                    _deleted
                    _lastChangedAt
                    deviceMetadataId
                  }
                  locationId
                  location {
                    id
                    value
                    type
                    parentID
                    parentHierarchy
                    parentName
                    accountID
                    createdAt
                    updatedAt
                    _version
                    _deleted
                    _lastChangedAt
                  }
                  accountID
                  createdAt
                  updatedAt
                  _version
                  _deleted
                  _lastChangedAt
                }
                commsVersion
                controllerVersion
                createdAt
                updatedAt
                _version
                _deleted
                _lastChangedAt
                deviceMetadataId
              }
              locationId
              location {
                id
                value
                type
                parentID
                parentHierarchy
                parentName
                accountID
                createdAt
                updatedAt
                _version
                _deleted
                _lastChangedAt
              }
              accountID
              createdAt
              updatedAt
              _version
              _deleted
              _lastChangedAt
            }
            commsVersion
            controllerVersion
            createdAt
            updatedAt
            _version
            _deleted
            _lastChangedAt
            deviceMetadataId
          }
          locationId
          location {
            id
            value
            type
            parentID
            parentHierarchy
            parentName
            accountID
            createdAt
            updatedAt
            _version
            _deleted
            _lastChangedAt
          }
          accountID
          createdAt
          updatedAt
          _version
          _deleted
          _lastChangedAt
        }
        commsVersion
        controllerVersion
        createdAt
        updatedAt
        _version
        _deleted
        _lastChangedAt
        deviceMetadataId
      }
      eventDate
      rawEvent
      accountID
      createdAt
      updatedAt
      _version
      _deleted
      _lastChangedAt
    }
  }
`;
export const onCreateUserPreference = /* GraphQL */ `
  subscription OnCreateUserPreference {
    onCreateUserPreference {
      id
      user_id
      dark_mode
      low_cartridge
      high_temperature
      low_temperature
      device_disconnected
      default_location
      createdAt
      updatedAt
      _version
      _deleted
      _lastChangedAt
    }
  }
`;
export const onUpdateUserPreference = /* GraphQL */ `
  subscription OnUpdateUserPreference {
    onUpdateUserPreference {
      id
      user_id
      dark_mode
      low_cartridge
      high_temperature
      low_temperature
      device_disconnected
      default_location
      createdAt
      updatedAt
      _version
      _deleted
      _lastChangedAt
    }
  }
`;
export const onDeleteUserPreference = /* GraphQL */ `
  subscription OnDeleteUserPreference {
    onDeleteUserPreference {
      id
      user_id
      dark_mode
      low_cartridge
      high_temperature
      low_temperature
      device_disconnected
      default_location
      createdAt
      updatedAt
      _version
      _deleted
      _lastChangedAt
    }
  }
`;
export const onCreateNotifications = /* GraphQL */ `
  subscription OnCreateNotifications {
    onCreateNotifications {
      id
      userPreferenceId
      token
      deviceId
      type
      value
      active
      lastSent
      isSeen
      isClicked
      accountID
      createdAt
      updatedAt
      _version
      _deleted
      _lastChangedAt
    }
  }
`;
export const onUpdateNotifications = /* GraphQL */ `
  subscription OnUpdateNotifications {
    onUpdateNotifications {
      id
      userPreferenceId
      token
      deviceId
      type
      value
      active
      lastSent
      isSeen
      isClicked
      accountID
      createdAt
      updatedAt
      _version
      _deleted
      _lastChangedAt
    }
  }
`;
export const onDeleteNotifications = /* GraphQL */ `
  subscription OnDeleteNotifications {
    onDeleteNotifications {
      id
      userPreferenceId
      token
      deviceId
      type
      value
      active
      lastSent
      isSeen
      isClicked
      accountID
      createdAt
      updatedAt
      _version
      _deleted
      _lastChangedAt
    }
  }
`;
